export default [
  {
    name: 'Open Book',
    github_url: 'https://github.com/Open-Book-LMS',
    url: 'https://openbook.digital',
    img_url: '',
    logo_url: '../../static/openbook/logo copy.png',
    description: 'A lightweight, highly customizable Learning Management System that allows educators to load just the tools they need for their content. Built with ease of use in mind. First iteration demo includes a live drawing demonstration tool for art education.',
    tech: ['Vue.js', 'Node.js', 'Express', 'PostgreSQL', 'Knex', 'MongoDB', 'Monk', 'Socket.io', 'HTML Canvas'],
  },
  {
    name: 'Little Bird - Dashboard Prototype',
    github_url: 'https://github.com/Little-bird-dashboard',
    url: 'https://littlebird.host',
    img_url: '',
    logo_url: '../../static/littlebird/little_bird.png',
    description: 'This project for Little Bird focused on creating the dashboard view for coordinators and the scheduling poll.',
    tech: ['HTML', 'Bootstrap CSS', 'Vue.js', 'Twilio', 'Node.js', 'Express', 'PostgreSQL'],
  },
  {
    name: 'Little Helpers',
    github_url: 'https://github.com/Parent-Pals',
    url: 'https://littlehelpers.world',
    img_url: '',
    logo_url: '../../static/littlehelpers/hand.png',
    description: 'This is a task-reward tracker geared towards young children and their parents.',
    tech: ['HTML', 'Bootstrap CSS', 'JavaScript', 'jQuery', 'Handlebars', 'Node.js', 'Express', 'Knex', 'PostgreSQL'],
  },
  {
    name: 'Word Race',
    img_url: '',
    github_url: 'https://github.com/baker-marlena/Word-Race',
    url: 'https://wordrace.online',
    logo_url: '../../static/wordrace/wordrace.png',
    description: 'A web app to help writers work together for greater motivation all around.',
    tech: ['HTML', 'Materialize CSS', 'JavaScript', 'jQuery', 'Firebase Realtime Database'],
  },
  {
    name: 'Little Bird - SWEDU Demo',
    github_url: 'https://github.com/exceptionalEducation',
    url: '',
    img_url: '',
    logo_url: '../../static/littlebird/little_bird-swedu.png',
    description: 'Little Bird is a web and SMS based app that aims to improve parent attendance at IEP meetings while lowering the logistical lift for Special Education teachers so they can focus on education.',
    tech: ['Twilio', 'Node.js', 'Express'],
  },
  {
    name: 'MarkClarity - Startup Weekend Women Prototype',
    github_url: 'https://github.com/Mark-Clarity',
    url: 'http://markclarity.surge.sh/#/',
    img_url: '',
    logo_url: '',
    description: 'MarkClarity is a website that provides quick and easy trademark searching for entrepreneurs who are in the ideation stage. MarkClarity checks state and federal risk, providing easy risk assesment for business names. Over the course of the weekend I put together the frontend of our prototype application, which was a functioning full stack application after two days of work. It pulled real data from the Colorado Secretary of State and a federal trademark search API. I also wrote the logic that determined, in simple terms, if the name carried a risk.',
    tech: ['Vue.js', 'vue-material', 'Python'],
  },
];
